export const drivers = [
  { driver: "Max Verstappen", team: "Red Bull Racing" },
  { driver: "Sergio Perez", team: "Red Bull Racing" },
  { driver: "Lewis Hamilton", team: "Mercedes" },
  { driver: "Fernando Alonso", team: "Aston Martin" },
  { driver: "Carlos Sainz", team: "Ferrari" },
  { driver: "Charles Leclerc", team: "Ferrari" },
  { driver: "Lando Norris", team: "McLaren" },
  { driver: "George Russell", team: "Mercedes" },
  { driver: "Oscar Piastri", team: "McLaren" },
  { driver: "Lance Stroll", team: "Aston Martin" },
  { driver: "Pierre Gasly", team: "Alpine" },
  { driver: "Esteban Ocon", team: "Alpine" },
  { driver: "Alexander Albon", team: "Williams" },
  { driver: "Valtteri Bottas", team: "Alfa Romeo" },
  { driver: "Nico Hulkenberg", team: "Haas F1 Team" },
  { driver: "Guanyu Zhou", team: "Alfa Romeo" },
  { driver: "Yuki Tsunoda", team: "AlphaTauri" },
  { driver: "Kevin Magnussen", team: "Haas F1 Team" },
  { driver: "Liam Lawson", team: "AlphaTauri" },
  { driver: "Logan Sargeant", team: "Williams" },
  { driver: "Nyck De Vries", team: "AlphaTauri" },
  { driver: "Daniel Ricciardo", team: "AlphaTauri" },
];
