export const players = [
  "Lewis Hamilton (Mercedes)",
  "Valtteri Bottas (Mercedes)",
  "Max Verstappen (Red Bull Racing)",
  "Sergio Perez (Red Bull Racing)",
  "Charles Leclerc (Ferrari)",
  "Carlos Sainz (Ferrari)",
  "Daniel Ricciardo (McLaren)",
  "Lando Norris (McLaren)",
  "Fernando Alonso (Alpine)",
  "Esteban Ocon (Alpine)",
  "Sebastian Vettel (Aston Martin)",
  "Lance Stroll (Aston Martin)",
  "Pierre Gasly (AlphaTauri)",
  "Yuki Tsunoda (AlphaTauri)",
  "Kimi Räikkönen (Alfa Romeo)",
  "Antonio Giovinazzi (Alfa Romeo)",
  "Nikita Mazepin (Haas)",
  "Mick Schumacher (Haas)",
  "Nicholas Latifi (Williams)",
  "George Russell (Williams)",
];
